name: Push to Another Repository

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出源代码
      - name: Checkout source code
        uses: actions/checkout@v4
        
      # 2. 配置 Git 用户信息（可选）
      - name: Set Git user
        run: |
          git config --global user.name "zhoudq"
          git config --global user.email "zhoudq@cn.ibm.com"

      # 2. 测试 PAT 是否有效
      - name: Test PAT (API)
        run: |
          curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{ secrets.TARGET_REPO_TOKEN }}" \
            https://api.github.com/repos/${{ secrets.TARGET_REPO_OWNER }}/${{ secrets.TARGET_REPO_NAME }}
          echo "HTTP Status Code: $?"

      # 3. 添加目标仓库为远程仓库（使用 HTTPS + PAT）
      - name: Add target repository as remote
        run: |
          git push https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/${{ secrets.TARGET_REPO_OWNER }}/${{ secrets.TARGET_REPO_NAME }}.git main
