name: Push to Another Repository

on:
  push:
    branches:
      - main  # 触发分支

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出源代码
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. 配置 Git 用户信息（可选）
      - name: Set Git user
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"

      # 3. 添加目标仓库为远程仓库（使用 PAT 认证）
      - name: Add target repository as remote
        run: |
          git remote add target https://${{ secrets.TARGET_REPO_TOKEN }}@github.com/${{ secrets.TARGET_REPO_OWNER }}/${{ secrets.TARGET_REPO_NAME }}.git

      # 4. 推送代码到目标仓库
      - name: Push to target repository
        run: |
          git push target main  # 推送 main 分支