name: Push to Another Repository

on:
  push:
    branches:
      - main

permissions:
  contents: read  # 允许 checkout 操作

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出源代码
      - name: Checkout source code
        uses: actions/checkout@v4
           
      # 2. 配置 Git 用户信息
      - name: Set Git user
        run: |
          git config --global user.name "zhoudq"
          git config --global user.email "zhoudq@cn.ibm.com"

      # 3. 测试 PAT 是否有效（通过 GitHub API）
      - name: Test PAT (API)
        id: test_pat
        run: |
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{ secrets.TARGET_REPO_TOKEN }}" \
            https://api.github.com/repos/${{ secrets.TARGET_REPO_OWNER }}/${{ secrets.TARGET_REPO_NAME }})
          if [ "$HTTP_CODE" -ne 200 ]; then
            echo "API Test failed with HTTP code $HTTP_CODE"
            exit 1
          fi
          echo "API Test succeeded with HTTP code $HTTP_CODE"

      # 4. 调用调试脚本进行推送
      - name: Push to target repository
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
          TARGET_REPO_OWNER: ${{ secrets.TARGET_REPO_OWNER }}
          TARGET_REPO_NAME: ${{ secrets.TARGET_REPO_NAME }}
        run: |
          chmod +x ./push_to_target.sh
          ./push_to_target.sh