name: Push to Another Repository

on:
  push:
    branches:
      - main  # 触发分支

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出源代码
      - name: Checkout source code
        uses: actions/checkout@v4


      # 3. 添加目标仓库为远程仓库（使用 PAT 认证）
      - name: Add target repository as remote
        run: |
          git remote add target https://${{ secrets.TARGET_REPO_TOKEN }}@github.com/zhoudeqiang9527/react-demo.git

      # 4. 推送代码到目标仓库
      - name: Push to target repository
        run: |
          git push target main  # 推送 main 分支